title: 'ServerlessSpy'
project: 'ServerlessSpy'
description: 'CDK-based library for writing elegant integration tests on AWS serverless architecture and additional web console to monitor events in real-time.'
author: Marko (ServerlessLife)
email: marko@serverlesslife.com
image: logo/full_logo.png
twitter_username: ServerlessL
github_username: serverlesslife
show_downloads: false
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true # Auto-generate ID's for headings
future: true
jailed: false
gfm_quirks: paragraph_end
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: dark
teaser: /logo/full_logo.svg
logo: /logo/full_logo.svg
markdown: kramdown
sass:
  # Where you keep your scss files
  sass_dir: assets/css/
  # Where sass should look for other scss
  load_paths:
    - node_modules/
exclude:
  - node_modules
  - test/node_modules
  - vendor
repository: ServerlessLife/serverless-spy
baseurl: /
include:
  - CONTRIBUTING.md
  - CODE_OF_CONDUCT.md
  - LICENSE.md
analytics:
  provider: 'google-gtag'
  google:
    tracking_id: 'G-C2PHH6WYPP'
